spring:
  main:
    web-application-type: servlet
  security:
    oauth2:
      client:
        registration:
          blizzard:
            client-id:
            client-secret:
            client-name: Battle.net OAuth Sample Client
            scope: openid,sc2.profile
        provider:
          blizzard:
            issuer-uri: https://oauth.battle.net
  thymeleaf:
    cache: false

blizzard:
  api:
    host: https://us.api.blizzard.com

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
